version: "3"
services:

  # neo4j:
  #   image: neo4j
  #   ports:
  #     - 7474:7474
  #     - 7687:7687
  #   volumes:
  #     - neo4jdata:/data

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379

  mongo:
    image: mongo
    ports:
      - 27017:27017

  fake:
    build: .
    volumes:
      - .:/app
    command: node src/index
    environment:
      NODE_ENV: $NODE_ENV
      NODE_SCRIPT: fake
      DEBUG_APP: server
      DEBUG: "server:*"
    ports:
      - 5000:5000

  service:
    build: .
    volumes:
      - .:/app
    command: node src/index
    environment:
      QUERY: ${QUERY}
      RC_REDIS_HOST: redis
      RC_REDIS_PORT: 6379
      NODE_ENV: $NODE_ENV
      NODE_SCRIPT: app
      DEBUG_APP: importer
      DEBUG: "importer:*"


volumes:
  neo4jdata:
